DZ_6
ESKrasnov/Hillel-homework pull request #6
Opened 2022-04-26 12:38 UTC by ESKrasnov

DZ_6

2022-04-26 13:56 UTC, ESKrasnov commented
последние 2 строчки перепроверка  что данные с файла удалились

2022-04-27 18:34 UTC, mmykhailenko requested changes
Задача 2 реализована не согласно условию

2022-05-04 21:30 UTC, mmykhailenko approved these changes

2022-05-04 21:30 UTC, mmykhailenko commented on DZ_6.py
> +            print(f.read())
if the file does not exist, will be raised exception. So, better check if file exist or not

2022-05-07 09:35 UTC, merged